language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
script: npm install istanbul && npm run-script test-on-travis
after_success:
  - npm install codeclimate-test-reporter && codeclimate-test-reporter < ./coverage/lcov.info
